services:
  api-monitor-go:
    image: lming001/api-monitor-go:tagname
    pull_policy: always
    platform: linux/amd64
    container_name: api-monitor-go
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - LOG_CLEANUP_ENABLED=1
      - LOG_MAX_SIZE_MB=128
      - API_MONITOR_TOKEN=${API_MONITOR_TOKEN:-}
      - ADMIN_PANEL_PASSWORD=${ADMIN_PANEL_PASSWORD:-}
    volumes:
      - ./data:/app/data
